group: travis_latest
language: python
cache: pip
python:
    - 3.6
install:
    - pip install -U pip
    - pip install --progress-bar off $(grep -Ev "apex|benepar*" requirements.txt)
    - pip install flake8 

before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --exclude matcher_elmo.py --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - "./tests/test.sh" 
notifications:
    on_success: change
    on_failure: change 